### ISSUE TITLE
SPOTIFY

### ISSUE THREAD

**Issue by PANOSSS1980** [pazfelipe/react-spotify-clone#1]
HELLO MEN!!!HAPPY EASTER!!!TELL ME PLEASE THIS IS FOR SEARCH MUSIC SONGS AND ALBUMS FROM SPOTIFY?

**Comment by pazfelipe** [comment]
Hey dude. It's not. It's just a **layout based app**. _There's no functionality_, only visual and a bit of js to reproduce some animations from _spotify_.
